# Generated by Django 3.2.11 on 2023-01-20 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iacademy', '0002_certificate_delete_certificato'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2023, 1, 20)),
        ),
    ]
